-- =============================================================================
-- mart.sku_portfolio_size — SKU Performance Analysis with Size Breakdown
-- =============================================================================
-- Purpose:  Same as sku_portfolio but at SIZE level (kode_besar grain)
-- Grain:    One row per kode_besar (SKU with size, e.g., "MEN-STR-BLK-40")
-- Columns:  107 active columns (11 ID/Base + 83 Sales + 13 Stock)
-- Refresh:  Snapshot table — rebuild daily/periodically via TRUNCATE + INSERT
-- Author:   Generated by Iris
-- Date:     2026-02-17
--
-- KEY DIFFERENCES FROM sku_portfolio:
--   1. Grain: kode_besar (with size) vs kodemix (article level, no size)
--   2. GROUP 1 expanded: Added kode_kecil, kode_mix_size, size columns
--   3. kode_besar = UNIQUE (enforced), kodemix will repeat (multiple sizes per article)
--   4. Sales/Stock aggregated by kode_besar (not kodemix)
--
-- BUSINESS RULES (SAME as sku_portfolio):
--   1. Sales exclude is_intercompany = TRUE
--   2. Sales exclude non-product items (SHOPPING BAG, HANGER, etc.)
--   3. Year auto-detected: current_year = EXTRACT(YEAR FROM CURRENT_DATE)
--   4. All entitas combined (DDD, MBB, UBB, LJBB)
--   5. tier = COALESCE(tier_baru, tier_lama, '3')
--   6. Stock channels mapped by nama_gudang pattern matching
--   7. avg_last_3_months = avg monthly qty in last 3 complete months
--   8. Turnover (TO) = stock / avg_monthly_sales
--
-- DATA SOURCES:
--   - Articles: portal.kodemix (DISTINCT ON kode_besar)
--   - Sales: core.sales_with_product (all entitas, GROUP BY kode_besar)
--   - Stock: core.stock_with_product (latest snapshot, GROUP BY kode_besar)
-- =============================================================================


-- =============================================================================
-- SECTION 1: DDL — CREATE TABLE
-- =============================================================================

DROP TABLE IF EXISTS mart.sku_portfolio_size;

CREATE TABLE mart.sku_portfolio_size (
    -- GROUP 1: ID / Base (11 columns)
    id                  SERIAL PRIMARY KEY,
    kode_besar          TEXT NOT NULL UNIQUE,  -- KUNCI UTAMA (SKU with size)
    kode_kecil          TEXT,                   -- Will repeat across sizes
    kode_mix_size       TEXT,                   -- Will repeat across sizes
    kodemix             TEXT,                   -- Will repeat across sizes (article level)
    gender              TEXT,
    series              TEXT,
    color               TEXT,
    tipe                TEXT,
    tier                TEXT,
    size                TEXT,                   -- 39, 40, 41, 42, 43/44, etc.

    -- GROUP 2: Year Labels (2 columns)
    current_year_label  TEXT NOT NULL,
    last_year_label     TEXT NOT NULL,

    -- GROUP 2: Monthly Sales — January (6 columns)
    now_jan_rp          NUMERIC(15,2) DEFAULT 0,
    last_jan_rp         NUMERIC(15,2) DEFAULT 0,
    var_jan_rp          NUMERIC(7,2),
    now_jan_qty         INTEGER DEFAULT 0,
    last_jan_qty        INTEGER DEFAULT 0,
    var_jan_qty         NUMERIC(7,2),

    -- GROUP 2: Monthly Sales — February (6 columns)
    now_feb_rp          NUMERIC(15,2) DEFAULT 0,
    last_feb_rp         NUMERIC(15,2) DEFAULT 0,
    var_feb_rp          NUMERIC(7,2),
    now_feb_qty         INTEGER DEFAULT 0,
    last_feb_qty        INTEGER DEFAULT 0,
    var_feb_qty         NUMERIC(7,2),

    -- GROUP 2: Monthly Sales — March (6 columns)
    now_mar_rp          NUMERIC(15,2) DEFAULT 0,
    last_mar_rp         NUMERIC(15,2) DEFAULT 0,
    var_mar_rp          NUMERIC(7,2),
    now_mar_qty         INTEGER DEFAULT 0,
    last_mar_qty        INTEGER DEFAULT 0,
    var_mar_qty         NUMERIC(7,2),

    -- GROUP 2: Monthly Sales — April (6 columns)
    now_apr_rp          NUMERIC(15,2) DEFAULT 0,
    last_apr_rp         NUMERIC(15,2) DEFAULT 0,
    var_apr_rp          NUMERIC(7,2),
    now_apr_qty         INTEGER DEFAULT 0,
    last_apr_qty        INTEGER DEFAULT 0,
    var_apr_qty         NUMERIC(7,2),

    -- GROUP 2: Monthly Sales — May (6 columns)
    now_may_rp          NUMERIC(15,2) DEFAULT 0,
    last_may_rp         NUMERIC(15,2) DEFAULT 0,
    var_may_rp          NUMERIC(7,2),
    now_may_qty         INTEGER DEFAULT 0,
    last_may_qty        INTEGER DEFAULT 0,
    var_may_qty         NUMERIC(7,2),

    -- GROUP 2: Monthly Sales — June (6 columns)
    now_jun_rp          NUMERIC(15,2) DEFAULT 0,
    last_jun_rp         NUMERIC(15,2) DEFAULT 0,
    var_jun_rp          NUMERIC(7,2),
    now_jun_qty         INTEGER DEFAULT 0,
    last_jun_qty        INTEGER DEFAULT 0,
    var_jun_qty         NUMERIC(7,2),

    -- GROUP 2: Monthly Sales — July (6 columns)
    now_jul_rp          NUMERIC(15,2) DEFAULT 0,
    last_jul_rp         NUMERIC(15,2) DEFAULT 0,
    var_jul_rp          NUMERIC(7,2),
    now_jul_qty         INTEGER DEFAULT 0,
    last_jul_qty        INTEGER DEFAULT 0,
    var_jul_qty         NUMERIC(7,2),

    -- GROUP 2: Monthly Sales — August (6 columns)
    now_aug_rp          NUMERIC(15,2) DEFAULT 0,
    last_aug_rp         NUMERIC(15,2) DEFAULT 0,
    var_aug_rp          NUMERIC(7,2),
    now_aug_qty         INTEGER DEFAULT 0,
    last_aug_qty        INTEGER DEFAULT 0,
    var_aug_qty         NUMERIC(7,2),

    -- GROUP 2: Monthly Sales — September (6 columns)
    now_sep_rp          NUMERIC(15,2) DEFAULT 0,
    last_sep_rp         NUMERIC(15,2) DEFAULT 0,
    var_sep_rp          NUMERIC(7,2),
    now_sep_qty         INTEGER DEFAULT 0,
    last_sep_qty        INTEGER DEFAULT 0,
    var_sep_qty         NUMERIC(7,2),

    -- GROUP 2: Monthly Sales — October (6 columns)
    now_oct_rp          NUMERIC(15,2) DEFAULT 0,
    last_oct_rp         NUMERIC(15,2) DEFAULT 0,
    var_oct_rp          NUMERIC(7,2),
    now_oct_qty         INTEGER DEFAULT 0,
    last_oct_qty        INTEGER DEFAULT 0,
    var_oct_qty         NUMERIC(7,2),

    -- GROUP 2: Monthly Sales — November (6 columns)
    now_nov_rp          NUMERIC(15,2) DEFAULT 0,
    last_nov_rp         NUMERIC(15,2) DEFAULT 0,
    var_nov_rp          NUMERIC(7,2),
    now_nov_qty         INTEGER DEFAULT 0,
    last_nov_qty        INTEGER DEFAULT 0,
    var_nov_qty         NUMERIC(7,2),

    -- GROUP 2: Monthly Sales — December (6 columns)
    now_dec_rp          NUMERIC(15,2) DEFAULT 0,
    last_dec_rp         NUMERIC(15,2) DEFAULT 0,
    var_dec_rp          NUMERIC(7,2),
    now_dec_qty         INTEGER DEFAULT 0,
    last_dec_qty        INTEGER DEFAULT 0,
    var_dec_qty         NUMERIC(7,2),

    -- GROUP 2: Year Totals (6 columns)
    current_year_rp     NUMERIC(15,2) DEFAULT 0,
    last_year_rp        NUMERIC(15,2) DEFAULT 0,
    var_year_rp         NUMERIC(7,2),
    current_year_qty    INTEGER DEFAULT 0,
    last_year_qty       INTEGER DEFAULT 0,
    var_year_qty        NUMERIC(7,2),

    -- GROUP 2: Sales Mix & Recent Performance (3 columns)
    current_sales_mix   NUMERIC(7,4),
    last_sales_mix      NUMERIC(7,4),
    avg_last_3_months   NUMERIC(10,2) DEFAULT 0,

    -- GROUP 3: Warehouse Stock (4 columns)
    wh_pusat            INTEGER DEFAULT 0,
    wh_bali             INTEGER DEFAULT 0,
    wh_jkt              INTEGER DEFAULT 0,
    wh_total            INTEGER DEFAULT 0,

    -- GROUP 3: Channel Stock (3 columns)
    stok_toko           INTEGER DEFAULT 0,
    stok_online         INTEGER DEFAULT 0,
    stok_unlabel        INTEGER DEFAULT 0,

    -- GROUP 3: Total Stock (1 column)
    stok_global         INTEGER DEFAULT 0,

    -- GROUP 3: Turnover (2 columns)
    to_wh               NUMERIC(10,2),
    to_total            NUMERIC(10,2),

    -- Metadata
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_sku_portfolio_size_kode_besar ON mart.sku_portfolio_size(kode_besar);
CREATE INDEX idx_sku_portfolio_size_kodemix ON mart.sku_portfolio_size(kodemix);
CREATE INDEX idx_sku_portfolio_size_gender ON mart.sku_portfolio_size(gender);
CREATE INDEX idx_sku_portfolio_size_tier ON mart.sku_portfolio_size(tier);
CREATE INDEX idx_sku_portfolio_size_size ON mart.sku_portfolio_size(size);

COMMENT ON TABLE mart.sku_portfolio_size IS 'SKU performance analysis at size level (kode_besar grain). One row per SKU with size breakdown. Rebuilt daily.';
COMMENT ON COLUMN mart.sku_portfolio_size.kode_besar IS 'PRIMARY KEY: Unique SKU identifier with size (e.g., MEN-STR-BLK-40)';
COMMENT ON COLUMN mart.sku_portfolio_size.kodemix IS 'Article identifier WITHOUT size (will repeat across multiple rows). Use for article-level aggregation.';
COMMENT ON COLUMN mart.sku_portfolio_size.size IS 'Size value: 39, 40, 41, 42, 43/44, etc.';


-- =============================================================================
-- SECTION 2: INSERT QUERY
-- =============================================================================

TRUNCATE TABLE mart.sku_portfolio_size;

INSERT INTO mart.sku_portfolio_size (
    -- GROUP 1
    kode_besar, kode_kecil, kode_mix_size, kodemix, gender, series, color, tipe, tier, size,
    -- GROUP 2
    current_year_label, last_year_label,
    now_jan_rp, last_jan_rp, var_jan_rp, now_jan_qty, last_jan_qty, var_jan_qty,
    now_feb_rp, last_feb_rp, var_feb_rp, now_feb_qty, last_feb_qty, var_feb_qty,
    now_mar_rp, last_mar_rp, var_mar_rp, now_mar_qty, last_mar_qty, var_mar_qty,
    now_apr_rp, last_apr_rp, var_apr_rp, now_apr_qty, last_apr_qty, var_apr_qty,
    now_may_rp, last_may_rp, var_may_rp, now_may_qty, last_may_qty, var_may_qty,
    now_jun_rp, last_jun_rp, var_jun_rp, now_jun_qty, last_jun_qty, var_jun_qty,
    now_jul_rp, last_jul_rp, var_jul_rp, now_jul_qty, last_jul_qty, var_jul_qty,
    now_aug_rp, last_aug_rp, var_aug_rp, now_aug_qty, last_aug_qty, var_aug_qty,
    now_sep_rp, last_sep_rp, var_sep_rp, now_sep_qty, last_sep_qty, var_sep_qty,
    now_oct_rp, last_oct_rp, var_oct_rp, now_oct_qty, last_oct_qty, var_oct_qty,
    now_nov_rp, last_nov_rp, var_nov_rp, now_nov_qty, last_nov_qty, var_nov_qty,
    now_dec_rp, last_dec_rp, var_dec_rp, now_dec_qty, last_dec_qty, var_dec_qty,
    current_year_rp, last_year_rp, var_year_rp, current_year_qty, last_year_qty, var_year_qty,
    current_sales_mix, last_sales_mix, avg_last_3_months,
    -- GROUP 3
    wh_pusat, wh_bali, wh_jkt, wh_total,
    stok_toko, stok_online, stok_unlabel, stok_global,
    to_wh, to_total
)
WITH 

-- CTE 1: Year variables (auto-detect)
years AS (
    SELECT 
        EXTRACT(YEAR FROM CURRENT_DATE)::INT AS current_year,
        (EXTRACT(YEAR FROM CURRENT_DATE) - 1)::INT AS last_year
),

-- CTE 2: Articles master (DISTINCT ON kode_besar)
articles AS (
    SELECT DISTINCT ON (UPPER(kode_besar))
        UPPER(kode_besar) AS kode_besar,
        kode AS kode_kecil,
        kode_mix_size,
        kode_mix AS kodemix,
        gender,
        series,
        color,
        tipe,
        COALESCE(tier_baru, tier_lama, '3') AS tier,
        COALESCE(size, ukuran) AS size
    FROM portal.kodemix
    WHERE kode_besar IS NOT NULL
      AND kode_besar != ''
    ORDER BY UPPER(kode_besar), no_urut DESC
),

-- CTE 3: Sales aggregated by kode_besar
sales_raw AS (
    SELECT 
        UPPER(kode_besar) AS kode_besar,
        EXTRACT(YEAR FROM transaction_date)::INT AS year,
        EXTRACT(MONTH FROM transaction_date)::INT AS month,
        SUM(total_amount) AS total_rp,
        SUM(quantity) AS total_qty
    FROM core.sales_with_product
    CROSS JOIN years
    WHERE EXTRACT(YEAR FROM transaction_date)::INT IN (years.current_year, years.last_year)
      AND is_intercompany = FALSE
      AND UPPER(article) NOT LIKE '%SHOPPING BAG%'
      AND UPPER(article) NOT LIKE '%HANGER%'
      AND UPPER(article) NOT LIKE '%PAPER BAG%'
      AND UPPER(article) NOT LIKE '%THERMAL%'
      AND UPPER(article) NOT LIKE '%BOX LUCA%'
      AND kode_besar IS NOT NULL
    GROUP BY UPPER(kode_besar), year, month
),

-- CTE 4: Monthly sales pivots (12 months × current/last year)
monthly_sales AS (
    SELECT 
        kode_besar,
        -- January
        SUM(CASE WHEN year = (SELECT current_year FROM years) AND month = 1 THEN total_rp ELSE 0 END) AS now_jan_rp,
        SUM(CASE WHEN year = (SELECT last_year FROM years) AND month = 1 THEN total_rp ELSE 0 END) AS last_jan_rp,
        SUM(CASE WHEN year = (SELECT current_year FROM years) AND month = 1 THEN total_qty ELSE 0 END) AS now_jan_qty,
        SUM(CASE WHEN year = (SELECT last_year FROM years) AND month = 1 THEN total_qty ELSE 0 END) AS last_jan_qty,
        -- February
        SUM(CASE WHEN year = (SELECT current_year FROM years) AND month = 2 THEN total_rp ELSE 0 END) AS now_feb_rp,
        SUM(CASE WHEN year = (SELECT last_year FROM years) AND month = 2 THEN total_rp ELSE 0 END) AS last_feb_rp,
        SUM(CASE WHEN year = (SELECT current_year FROM years) AND month = 2 THEN total_qty ELSE 0 END) AS now_feb_qty,
        SUM(CASE WHEN year = (SELECT last_year FROM years) AND month = 2 THEN total_qty ELSE 0 END) AS last_feb_qty,
        -- March
        SUM(CASE WHEN year = (SELECT current_year FROM years) AND month = 3 THEN total_rp ELSE 0 END) AS now_mar_rp,
        SUM(CASE WHEN year = (SELECT last_year FROM years) AND month = 3 THEN total_rp ELSE 0 END) AS last_mar_rp,
        SUM(CASE WHEN year = (SELECT current_year FROM years) AND month = 3 THEN total_qty ELSE 0 END) AS now_mar_qty,
        SUM(CASE WHEN year = (SELECT last_year FROM years) AND month = 3 THEN total_qty ELSE 0 END) AS last_mar_qty,
        -- April
        SUM(CASE WHEN year = (SELECT current_year FROM years) AND month = 4 THEN total_rp ELSE 0 END) AS now_apr_rp,
        SUM(CASE WHEN year = (SELECT last_year FROM years) AND month = 4 THEN total_rp ELSE 0 END) AS last_apr_rp,
        SUM(CASE WHEN year = (SELECT current_year FROM years) AND month = 4 THEN total_qty ELSE 0 END) AS now_apr_qty,
        SUM(CASE WHEN year = (SELECT last_year FROM years) AND month = 4 THEN total_qty ELSE 0 END) AS last_apr_qty,
        -- May
        SUM(CASE WHEN year = (SELECT current_year FROM years) AND month = 5 THEN total_rp ELSE 0 END) AS now_may_rp,
        SUM(CASE WHEN year = (SELECT last_year FROM years) AND month = 5 THEN total_rp ELSE 0 END) AS last_may_rp,
        SUM(CASE WHEN year = (SELECT current_year FROM years) AND month = 5 THEN total_qty ELSE 0 END) AS now_may_qty,
        SUM(CASE WHEN year = (SELECT last_year FROM years) AND month = 5 THEN total_qty ELSE 0 END) AS last_may_qty,
        -- June
        SUM(CASE WHEN year = (SELECT current_year FROM years) AND month = 6 THEN total_rp ELSE 0 END) AS now_jun_rp,
        SUM(CASE WHEN year = (SELECT last_year FROM years) AND month = 6 THEN total_rp ELSE 0 END) AS last_jun_rp,
        SUM(CASE WHEN year = (SELECT current_year FROM years) AND month = 6 THEN total_qty ELSE 0 END) AS now_jun_qty,
        SUM(CASE WHEN year = (SELECT last_year FROM years) AND month = 6 THEN total_qty ELSE 0 END) AS last_jun_qty,
        -- July
        SUM(CASE WHEN year = (SELECT current_year FROM years) AND month = 7 THEN total_rp ELSE 0 END) AS now_jul_rp,
        SUM(CASE WHEN year = (SELECT last_year FROM years) AND month = 7 THEN total_rp ELSE 0 END) AS last_jul_rp,
        SUM(CASE WHEN year = (SELECT current_year FROM years) AND month = 7 THEN total_qty ELSE 0 END) AS now_jul_qty,
        SUM(CASE WHEN year = (SELECT last_year FROM years) AND month = 7 THEN total_qty ELSE 0 END) AS last_jul_qty,
        -- August
        SUM(CASE WHEN year = (SELECT current_year FROM years) AND month = 8 THEN total_rp ELSE 0 END) AS now_aug_rp,
        SUM(CASE WHEN year = (SELECT last_year FROM years) AND month = 8 THEN total_rp ELSE 0 END) AS last_aug_rp,
        SUM(CASE WHEN year = (SELECT current_year FROM years) AND month = 8 THEN total_qty ELSE 0 END) AS now_aug_qty,
        SUM(CASE WHEN year = (SELECT last_year FROM years) AND month = 8 THEN total_qty ELSE 0 END) AS last_aug_qty,
        -- September
        SUM(CASE WHEN year = (SELECT current_year FROM years) AND month = 9 THEN total_rp ELSE 0 END) AS now_sep_rp,
        SUM(CASE WHEN year = (SELECT last_year FROM years) AND month = 9 THEN total_rp ELSE 0 END) AS last_sep_rp,
        SUM(CASE WHEN year = (SELECT current_year FROM years) AND month = 9 THEN total_qty ELSE 0 END) AS now_sep_qty,
        SUM(CASE WHEN year = (SELECT last_year FROM years) AND month = 9 THEN total_qty ELSE 0 END) AS last_sep_qty,
        -- October
        SUM(CASE WHEN year = (SELECT current_year FROM years) AND month = 10 THEN total_rp ELSE 0 END) AS now_oct_rp,
        SUM(CASE WHEN year = (SELECT last_year FROM years) AND month = 10 THEN total_rp ELSE 0 END) AS last_oct_rp,
        SUM(CASE WHEN year = (SELECT current_year FROM years) AND month = 10 THEN total_qty ELSE 0 END) AS now_oct_qty,
        SUM(CASE WHEN year = (SELECT last_year FROM years) AND month = 10 THEN total_qty ELSE 0 END) AS last_oct_qty,
        -- November
        SUM(CASE WHEN year = (SELECT current_year FROM years) AND month = 11 THEN total_rp ELSE 0 END) AS now_nov_rp,
        SUM(CASE WHEN year = (SELECT last_year FROM years) AND month = 11 THEN total_rp ELSE 0 END) AS last_nov_rp,
        SUM(CASE WHEN year = (SELECT current_year FROM years) AND month = 11 THEN total_qty ELSE 0 END) AS now_nov_qty,
        SUM(CASE WHEN year = (SELECT last_year FROM years) AND month = 11 THEN total_qty ELSE 0 END) AS last_nov_qty,
        -- December
        SUM(CASE WHEN year = (SELECT current_year FROM years) AND month = 12 THEN total_rp ELSE 0 END) AS now_dec_rp,
        SUM(CASE WHEN year = (SELECT last_year FROM years) AND month = 12 THEN total_rp ELSE 0 END) AS last_dec_rp,
        SUM(CASE WHEN year = (SELECT current_year FROM years) AND month = 12 THEN total_qty ELSE 0 END) AS now_dec_qty,
        SUM(CASE WHEN year = (SELECT last_year FROM years) AND month = 12 THEN total_qty ELSE 0 END) AS last_dec_qty
    FROM sales_raw
    GROUP BY kode_besar
),

-- CTE 5: Year totals
year_totals AS (
    SELECT 
        kode_besar,
        SUM(CASE WHEN year = (SELECT current_year FROM years) THEN total_rp ELSE 0 END) AS current_year_rp,
        SUM(CASE WHEN year = (SELECT last_year FROM years) THEN total_rp ELSE 0 END) AS last_year_rp,
        SUM(CASE WHEN year = (SELECT current_year FROM years) THEN total_qty ELSE 0 END) AS current_year_qty,
        SUM(CASE WHEN year = (SELECT last_year FROM years) THEN total_qty ELSE 0 END) AS last_year_qty
    FROM sales_raw
    GROUP BY kode_besar
),

-- CTE 6: Grand totals (for sales mix calculation)
grand_totals AS (
    SELECT 
        SUM(CASE WHEN year = (SELECT current_year FROM years) THEN total_rp ELSE 0 END) AS current_year_total_rp,
        SUM(CASE WHEN year = (SELECT last_year FROM years) THEN total_rp ELSE 0 END) AS last_year_total_rp
    FROM sales_raw
),

-- CTE 7: Last 3 complete months average
avg_3mo AS (
    SELECT 
        kode_besar,
        AVG(total_qty) AS avg_last_3_months
    FROM sales_raw
    WHERE year = (SELECT current_year FROM years)
      AND month IN (
          EXTRACT(MONTH FROM CURRENT_DATE - INTERVAL '1 month')::INT,
          EXTRACT(MONTH FROM CURRENT_DATE - INTERVAL '2 months')::INT,
          EXTRACT(MONTH FROM CURRENT_DATE - INTERVAL '3 months')::INT
      )
    GROUP BY kode_besar
),

-- CTE 8: Stock aggregated by kode_besar
stock_raw AS (
    SELECT 
        UPPER(kode_besar) AS kode_besar,
        nama_gudang,
        gudang_category,
        SUM(quantity) AS quantity
    FROM core.stock_with_product
    WHERE snapshot_date = (SELECT MAX(snapshot_date) FROM core.stock_with_product)
      AND kode_besar IS NOT NULL
    GROUP BY UPPER(kode_besar), nama_gudang, gudang_category
),

-- CTE 9: Stock breakdown by channel
stock_channels AS (
    SELECT 
        kode_besar,
        -- Warehouse breakdown
        SUM(CASE 
            WHEN LOWER(nama_gudang) LIKE '%warehouse pusat%' 
             AND LOWER(nama_gudang) NOT LIKE '%reject%' 
            THEN quantity ELSE 0 
        END) AS wh_pusat,
        SUM(CASE 
            WHEN LOWER(nama_gudang) LIKE '%warehouse bali%' 
             AND LOWER(nama_gudang) NOT LIKE '%reject%' 
            THEN quantity ELSE 0 
        END) AS wh_bali,
        SUM(CASE 
            WHEN (LOWER(nama_gudang) LIKE '%warehouse pluit%' 
               OR LOWER(nama_gudang) LIKE '%warehouse jakarta%'
               OR LOWER(nama_gudang) LIKE '%warehouse palembang%')
             AND LOWER(nama_gudang) NOT LIKE '%reject%' 
            THEN quantity ELSE 0 
        END) AS wh_jkt,
        -- Channel breakdown
        SUM(CASE 
            WHEN gudang_category = 'RETAIL' 
            THEN quantity ELSE 0 
        END) AS stok_toko,
        SUM(CASE 
            WHEN LOWER(nama_gudang) LIKE '%online%' 
              OR LOWER(nama_gudang) LIKE '%agency%'
              OR LOWER(nama_gudang) LIKE '%shopee%'
            THEN quantity ELSE 0 
        END) AS stok_online,
        -- Unlabel (everything else: events, wholesale, consignment, etc.)
        SUM(CASE 
            WHEN gudang_category NOT IN ('RETAIL')
             AND LOWER(nama_gudang) NOT LIKE '%warehouse pusat%'
             AND LOWER(nama_gudang) NOT LIKE '%warehouse bali%'
             AND LOWER(nama_gudang) NOT LIKE '%warehouse pluit%'
             AND LOWER(nama_gudang) NOT LIKE '%warehouse jakarta%'
             AND LOWER(nama_gudang) NOT LIKE '%warehouse palembang%'
             AND LOWER(nama_gudang) NOT LIKE '%online%'
             AND LOWER(nama_gudang) NOT LIKE '%agency%'
             AND LOWER(nama_gudang) NOT LIKE '%shopee%'
            THEN quantity ELSE 0 
        END) AS stok_unlabel
    FROM stock_raw
    GROUP BY kode_besar
)

-- FINAL SELECT: Join all CTEs
SELECT 
    -- GROUP 1
    a.kode_besar,
    a.kode_kecil,
    a.kode_mix_size,
    a.kodemix,
    a.gender,
    a.series,
    a.color,
    a.tipe,
    a.tier,
    a.size,
    
    -- GROUP 2: Year labels
    (SELECT current_year::TEXT FROM years) AS current_year_label,
    (SELECT last_year::TEXT FROM years) AS last_year_label,
    
    -- GROUP 2: Monthly sales
    COALESCE(m.now_jan_rp, 0) AS now_jan_rp,
    COALESCE(m.last_jan_rp, 0) AS last_jan_rp,
    CASE WHEN COALESCE(m.last_jan_rp, 0) > 0 
         THEN ROUND(((COALESCE(m.now_jan_rp, 0) - COALESCE(m.last_jan_rp, 0)) / COALESCE(m.last_jan_rp, 1)) * 100, 2)
         ELSE NULL END AS var_jan_rp,
    COALESCE(m.now_jan_qty, 0) AS now_jan_qty,
    COALESCE(m.last_jan_qty, 0) AS last_jan_qty,
    CASE WHEN COALESCE(m.last_jan_qty, 0) > 0 
         THEN ROUND(((COALESCE(m.now_jan_qty, 0) - COALESCE(m.last_jan_qty, 0))::NUMERIC / COALESCE(m.last_jan_qty, 1)) * 100, 2)
         ELSE NULL END AS var_jan_qty,
    
    COALESCE(m.now_feb_rp, 0) AS now_feb_rp,
    COALESCE(m.last_feb_rp, 0) AS last_feb_rp,
    CASE WHEN COALESCE(m.last_feb_rp, 0) > 0 
         THEN ROUND(((COALESCE(m.now_feb_rp, 0) - COALESCE(m.last_feb_rp, 0)) / COALESCE(m.last_feb_rp, 1)) * 100, 2)
         ELSE NULL END AS var_feb_rp,
    COALESCE(m.now_feb_qty, 0) AS now_feb_qty,
    COALESCE(m.last_feb_qty, 0) AS last_feb_qty,
    CASE WHEN COALESCE(m.last_feb_qty, 0) > 0 
         THEN ROUND(((COALESCE(m.now_feb_qty, 0) - COALESCE(m.last_feb_qty, 0))::NUMERIC / COALESCE(m.last_feb_qty, 1)) * 100, 2)
         ELSE NULL END AS var_feb_qty,
    
    COALESCE(m.now_mar_rp, 0) AS now_mar_rp,
    COALESCE(m.last_mar_rp, 0) AS last_mar_rp,
    CASE WHEN COALESCE(m.last_mar_rp, 0) > 0 
         THEN ROUND(((COALESCE(m.now_mar_rp, 0) - COALESCE(m.last_mar_rp, 0)) / COALESCE(m.last_mar_rp, 1)) * 100, 2)
         ELSE NULL END AS var_mar_rp,
    COALESCE(m.now_mar_qty, 0) AS now_mar_qty,
    COALESCE(m.last_mar_qty, 0) AS last_mar_qty,
    CASE WHEN COALESCE(m.last_mar_qty, 0) > 0 
         THEN ROUND(((COALESCE(m.now_mar_qty, 0) - COALESCE(m.last_mar_qty, 0))::NUMERIC / COALESCE(m.last_mar_qty, 1)) * 100, 2)
         ELSE NULL END AS var_mar_qty,
    
    COALESCE(m.now_apr_rp, 0) AS now_apr_rp,
    COALESCE(m.last_apr_rp, 0) AS last_apr_rp,
    CASE WHEN COALESCE(m.last_apr_rp, 0) > 0 
         THEN ROUND(((COALESCE(m.now_apr_rp, 0) - COALESCE(m.last_apr_rp, 0)) / COALESCE(m.last_apr_rp, 1)) * 100, 2)
         ELSE NULL END AS var_apr_rp,
    COALESCE(m.now_apr_qty, 0) AS now_apr_qty,
    COALESCE(m.last_apr_qty, 0) AS last_apr_qty,
    CASE WHEN COALESCE(m.last_apr_qty, 0) > 0 
         THEN ROUND(((COALESCE(m.now_apr_qty, 0) - COALESCE(m.last_apr_qty, 0))::NUMERIC / COALESCE(m.last_apr_qty, 1)) * 100, 2)
         ELSE NULL END AS var_apr_qty,
    
    COALESCE(m.now_may_rp, 0) AS now_may_rp,
    COALESCE(m.last_may_rp, 0) AS last_may_rp,
    CASE WHEN COALESCE(m.last_may_rp, 0) > 0 
         THEN ROUND(((COALESCE(m.now_may_rp, 0) - COALESCE(m.last_may_rp, 0)) / COALESCE(m.last_may_rp, 1)) * 100, 2)
         ELSE NULL END AS var_may_rp,
    COALESCE(m.now_may_qty, 0) AS now_may_qty,
    COALESCE(m.last_may_qty, 0) AS last_may_qty,
    CASE WHEN COALESCE(m.last_may_qty, 0) > 0 
         THEN ROUND(((COALESCE(m.now_may_qty, 0) - COALESCE(m.last_may_qty, 0))::NUMERIC / COALESCE(m.last_may_qty, 1)) * 100, 2)
         ELSE NULL END AS var_may_qty,
    
    COALESCE(m.now_jun_rp, 0) AS now_jun_rp,
    COALESCE(m.last_jun_rp, 0) AS last_jun_rp,
    CASE WHEN COALESCE(m.last_jun_rp, 0) > 0 
         THEN ROUND(((COALESCE(m.now_jun_rp, 0) - COALESCE(m.last_jun_rp, 0)) / COALESCE(m.last_jun_rp, 1)) * 100, 2)
         ELSE NULL END AS var_jun_rp,
    COALESCE(m.now_jun_qty, 0) AS now_jun_qty,
    COALESCE(m.last_jun_qty, 0) AS last_jun_qty,
    CASE WHEN COALESCE(m.last_jun_qty, 0) > 0 
         THEN ROUND(((COALESCE(m.now_jun_qty, 0) - COALESCE(m.last_jun_qty, 0))::NUMERIC / COALESCE(m.last_jun_qty, 1)) * 100, 2)
         ELSE NULL END AS var_jun_qty,
    
    COALESCE(m.now_jul_rp, 0) AS now_jul_rp,
    COALESCE(m.last_jul_rp, 0) AS last_jul_rp,
    CASE WHEN COALESCE(m.last_jul_rp, 0) > 0 
         THEN ROUND(((COALESCE(m.now_jul_rp, 0) - COALESCE(m.last_jul_rp, 0)) / COALESCE(m.last_jul_rp, 1)) * 100, 2)
         ELSE NULL END AS var_jul_rp,
    COALESCE(m.now_jul_qty, 0) AS now_jul_qty,
    COALESCE(m.last_jul_qty, 0) AS last_jul_qty,
    CASE WHEN COALESCE(m.last_jul_qty, 0) > 0 
         THEN ROUND(((COALESCE(m.now_jul_qty, 0) - COALESCE(m.last_jul_qty, 0))::NUMERIC / COALESCE(m.last_jul_qty, 1)) * 100, 2)
         ELSE NULL END AS var_jul_qty,
    
    COALESCE(m.now_aug_rp, 0) AS now_aug_rp,
    COALESCE(m.last_aug_rp, 0) AS last_aug_rp,
    CASE WHEN COALESCE(m.last_aug_rp, 0) > 0 
         THEN ROUND(((COALESCE(m.now_aug_rp, 0) - COALESCE(m.last_aug_rp, 0)) / COALESCE(m.last_aug_rp, 1)) * 100, 2)
         ELSE NULL END AS var_aug_rp,
    COALESCE(m.now_aug_qty, 0) AS now_aug_qty,
    COALESCE(m.last_aug_qty, 0) AS last_aug_qty,
    CASE WHEN COALESCE(m.last_aug_qty, 0) > 0 
         THEN ROUND(((COALESCE(m.now_aug_qty, 0) - COALESCE(m.last_aug_qty, 0))::NUMERIC / COALESCE(m.last_aug_qty, 1)) * 100, 2)
         ELSE NULL END AS var_aug_qty,
    
    COALESCE(m.now_sep_rp, 0) AS now_sep_rp,
    COALESCE(m.last_sep_rp, 0) AS last_sep_rp,
    CASE WHEN COALESCE(m.last_sep_rp, 0) > 0 
         THEN ROUND(((COALESCE(m.now_sep_rp, 0) - COALESCE(m.last_sep_rp, 0)) / COALESCE(m.last_sep_rp, 1)) * 100, 2)
         ELSE NULL END AS var_sep_rp,
    COALESCE(m.now_sep_qty, 0) AS now_sep_qty,
    COALESCE(m.last_sep_qty, 0) AS last_sep_qty,
    CASE WHEN COALESCE(m.last_sep_qty, 0) > 0 
         THEN ROUND(((COALESCE(m.now_sep_qty, 0) - COALESCE(m.last_sep_qty, 0))::NUMERIC / COALESCE(m.last_sep_qty, 1)) * 100, 2)
         ELSE NULL END AS var_sep_qty,
    
    COALESCE(m.now_oct_rp, 0) AS now_oct_rp,
    COALESCE(m.last_oct_rp, 0) AS last_oct_rp,
    CASE WHEN COALESCE(m.last_oct_rp, 0) > 0 
         THEN ROUND(((COALESCE(m.now_oct_rp, 0) - COALESCE(m.last_oct_rp, 0)) / COALESCE(m.last_oct_rp, 1)) * 100, 2)
         ELSE NULL END AS var_oct_rp,
    COALESCE(m.now_oct_qty, 0) AS now_oct_qty,
    COALESCE(m.last_oct_qty, 0) AS last_oct_qty,
    CASE WHEN COALESCE(m.last_oct_qty, 0) > 0 
         THEN ROUND(((COALESCE(m.now_oct_qty, 0) - COALESCE(m.last_oct_qty, 0))::NUMERIC / COALESCE(m.last_oct_qty, 1)) * 100, 2)
         ELSE NULL END AS var_oct_qty,
    
    COALESCE(m.now_nov_rp, 0) AS now_nov_rp,
    COALESCE(m.last_nov_rp, 0) AS last_nov_rp,
    CASE WHEN COALESCE(m.last_nov_rp, 0) > 0 
         THEN ROUND(((COALESCE(m.now_nov_rp, 0) - COALESCE(m.last_nov_rp, 0)) / COALESCE(m.last_nov_rp, 1)) * 100, 2)
         ELSE NULL END AS var_nov_rp,
    COALESCE(m.now_nov_qty, 0) AS now_nov_qty,
    COALESCE(m.last_nov_qty, 0) AS last_nov_qty,
    CASE WHEN COALESCE(m.last_nov_qty, 0) > 0 
         THEN ROUND(((COALESCE(m.now_nov_qty, 0) - COALESCE(m.last_nov_qty, 0))::NUMERIC / COALESCE(m.last_nov_qty, 1)) * 100, 2)
         ELSE NULL END AS var_nov_qty,
    
    COALESCE(m.now_dec_rp, 0) AS now_dec_rp,
    COALESCE(m.last_dec_rp, 0) AS last_dec_rp,
    CASE WHEN COALESCE(m.last_dec_rp, 0) > 0 
         THEN ROUND(((COALESCE(m.now_dec_rp, 0) - COALESCE(m.last_dec_rp, 0)) / COALESCE(m.last_dec_rp, 1)) * 100, 2)
         ELSE NULL END AS var_dec_rp,
    COALESCE(m.now_dec_qty, 0) AS now_dec_qty,
    COALESCE(m.last_dec_qty, 0) AS last_dec_qty,
    CASE WHEN COALESCE(m.last_dec_qty, 0) > 0 
         THEN ROUND(((COALESCE(m.now_dec_qty, 0) - COALESCE(m.last_dec_qty, 0))::NUMERIC / COALESCE(m.last_dec_qty, 1)) * 100, 2)
         ELSE NULL END AS var_dec_qty,
    
    -- GROUP 2: Year totals
    COALESCE(yt.current_year_rp, 0) AS current_year_rp,
    COALESCE(yt.last_year_rp, 0) AS last_year_rp,
    CASE WHEN COALESCE(yt.last_year_rp, 0) > 0 
         THEN ROUND(((COALESCE(yt.current_year_rp, 0) - COALESCE(yt.last_year_rp, 0)) / COALESCE(yt.last_year_rp, 1)) * 100, 2)
         ELSE NULL END AS var_year_rp,
    COALESCE(yt.current_year_qty, 0) AS current_year_qty,
    COALESCE(yt.last_year_qty, 0) AS last_year_qty,
    CASE WHEN COALESCE(yt.last_year_qty, 0) > 0 
         THEN ROUND(((COALESCE(yt.current_year_qty, 0) - COALESCE(yt.last_year_qty, 0))::NUMERIC / COALESCE(yt.last_year_qty, 1)) * 100, 2)
         ELSE NULL END AS var_year_qty,
    
    -- GROUP 2: Sales mix
    CASE WHEN (SELECT current_year_total_rp FROM grand_totals) > 0
         THEN ROUND((COALESCE(yt.current_year_rp, 0) / (SELECT current_year_total_rp FROM grand_totals)) * 100, 4)
         ELSE NULL END AS current_sales_mix,
    CASE WHEN (SELECT last_year_total_rp FROM grand_totals) > 0
         THEN ROUND((COALESCE(yt.last_year_rp, 0) / (SELECT last_year_total_rp FROM grand_totals)) * 100, 4)
         ELSE NULL END AS last_sales_mix,
    COALESCE(avg3.avg_last_3_months, 0) AS avg_last_3_months,
    
    -- GROUP 3: Stock
    COALESCE(sc.wh_pusat, 0) AS wh_pusat,
    COALESCE(sc.wh_bali, 0) AS wh_bali,
    COALESCE(sc.wh_jkt, 0) AS wh_jkt,
    (COALESCE(sc.wh_pusat, 0) + COALESCE(sc.wh_bali, 0) + COALESCE(sc.wh_jkt, 0)) AS wh_total,
    COALESCE(sc.stok_toko, 0) AS stok_toko,
    COALESCE(sc.stok_online, 0) AS stok_online,
    COALESCE(sc.stok_unlabel, 0) AS stok_unlabel,
    (COALESCE(sc.wh_pusat, 0) + COALESCE(sc.wh_bali, 0) + COALESCE(sc.wh_jkt, 0) + 
     COALESCE(sc.stok_toko, 0) + COALESCE(sc.stok_online, 0) + COALESCE(sc.stok_unlabel, 0)) AS stok_global,
    
    -- GROUP 3: Turnover
    CASE WHEN COALESCE(avg3.avg_last_3_months, 0) > 0
         THEN ROUND((COALESCE(sc.wh_pusat, 0) + COALESCE(sc.wh_bali, 0) + COALESCE(sc.wh_jkt, 0))::NUMERIC / 
                    COALESCE(avg3.avg_last_3_months, 1), 2)
         ELSE NULL END AS to_wh,
    CASE WHEN COALESCE(avg3.avg_last_3_months, 0) > 0
         THEN ROUND((COALESCE(sc.wh_pusat, 0) + COALESCE(sc.wh_bali, 0) + COALESCE(sc.wh_jkt, 0) + 
                     COALESCE(sc.stok_toko, 0) + COALESCE(sc.stok_online, 0) + COALESCE(sc.stok_unlabel, 0))::NUMERIC / 
                    COALESCE(avg3.avg_last_3_months, 1), 2)
         ELSE NULL END AS to_total

FROM articles a
LEFT JOIN monthly_sales m ON a.kode_besar = m.kode_besar
LEFT JOIN year_totals yt ON a.kode_besar = yt.kode_besar
LEFT JOIN avg_3mo avg3 ON a.kode_besar = avg3.kode_besar
LEFT JOIN stock_channels sc ON a.kode_besar = sc.kode_besar
CROSS JOIN grand_totals;

-- =============================================================================
-- SECTION 3: VERIFICATION QUERIES
-- =============================================================================

-- Count check
SELECT COUNT(*) AS total_rows FROM mart.sku_portfolio_size;

-- Sample data (first 10 rows)
SELECT * FROM mart.sku_portfolio_size LIMIT 10;

-- Check for duplicate kode_besar (should be 0)
SELECT kode_besar, COUNT(*) 
FROM mart.sku_portfolio_size 
GROUP BY kode_besar 
HAVING COUNT(*) > 1;

-- Check kodemix repeat pattern (same article, multiple sizes)
SELECT kodemix, COUNT(*) AS size_count
FROM mart.sku_portfolio_size
GROUP BY kodemix
HAVING COUNT(*) > 1
ORDER BY size_count DESC
LIMIT 10;

-- Top 10 SKUs by current year sales
SELECT kode_besar, kodemix, size, gender, series, color, 
       current_year_qty, current_year_rp, stok_global
FROM mart.sku_portfolio_size
WHERE current_year_qty > 0
ORDER BY current_year_qty DESC
LIMIT 10;
